/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.mavenClient.ui.form;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import rs.ac.bg.fon.ai.nprog.mavenClient.controller.Controller;

/**
 *
 * @author Ivona
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMain() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        Controller.getInstance().setfMain(this);
        jLblCurrentUser.setText(Controller.getInstance().getCurrentUser().getName() + " " + Controller.getInstance().getCurrentUser().getLastname());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLblCurrentUser = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuMovie = new javax.swing.JMenu();
        jMenuNewMovie = new javax.swing.JMenuItem();
        jMenuSearchMovie = new javax.swing.JMenuItem();
        jMenuShowtime = new javax.swing.JMenu();
        jMenuNewShowtime = new javax.swing.JMenuItem();
        jMenuSearchShowtime = new javax.swing.JMenuItem();
        jMenuTicketReservation = new javax.swing.JMenu();
        jMenuNewTicketReservation = new javax.swing.JMenuItem();
        jMenuSearchTicketReservation = new javax.swing.JMenuItem();
        jMenuMovieMarathon = new javax.swing.JMenu();
        jMenuNewMovieMarathon = new javax.swing.JMenuItem();
        jMenuSearchMovieMarathon = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");

        jLblCurrentUser.setBackground(new java.awt.Color(204, 204, 255));
        jLblCurrentUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLblCurrentUser.setForeground(new java.awt.Color(0, 0, 102));
        jLblCurrentUser.setText("     ");

        jMenuBar.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar.setForeground(new java.awt.Color(0, 0, 102));
        jMenuBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuMovie.setBackground(new java.awt.Color(153, 153, 255));
        jMenuMovie.setForeground(new java.awt.Color(0, 0, 102));
        jMenuMovie.setText("Film");

        jMenuNewMovie.setForeground(new java.awt.Color(0, 0, 102));
        jMenuNewMovie.setText("Novi");
        jMenuNewMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewMovieActionPerformed(evt);
            }
        });
        jMenuMovie.add(jMenuNewMovie);

        jMenuSearchMovie.setForeground(new java.awt.Color(0, 0, 102));
        jMenuSearchMovie.setText("Pretraži");
        jMenuSearchMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchMovieActionPerformed(evt);
            }
        });
        jMenuMovie.add(jMenuSearchMovie);

        jMenuBar.add(jMenuMovie);

        jMenuShowtime.setForeground(new java.awt.Color(0, 0, 102));
        jMenuShowtime.setText(" Projekcija");

        jMenuNewShowtime.setForeground(new java.awt.Color(0, 0, 102));
        jMenuNewShowtime.setText("Nova");
        jMenuNewShowtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewShowtimeActionPerformed(evt);
            }
        });
        jMenuShowtime.add(jMenuNewShowtime);

        jMenuSearchShowtime.setForeground(new java.awt.Color(0, 0, 102));
        jMenuSearchShowtime.setText("Pretraži");
        jMenuSearchShowtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchShowtimeActionPerformed(evt);
            }
        });
        jMenuShowtime.add(jMenuSearchShowtime);

        jMenuBar.add(jMenuShowtime);

        jMenuTicketReservation.setBackground(new java.awt.Color(153, 153, 255));
        jMenuTicketReservation.setForeground(new java.awt.Color(0, 0, 102));
        jMenuTicketReservation.setText("Rezervacija karte");

        jMenuNewTicketReservation.setForeground(new java.awt.Color(0, 0, 102));
        jMenuNewTicketReservation.setText("Nova");
        jMenuNewTicketReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewTicketReservationActionPerformed(evt);
            }
        });
        jMenuTicketReservation.add(jMenuNewTicketReservation);

        jMenuSearchTicketReservation.setForeground(new java.awt.Color(0, 0, 102));
        jMenuSearchTicketReservation.setText("Pretraži");
        jMenuSearchTicketReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchTicketReservationActionPerformed(evt);
            }
        });
        jMenuTicketReservation.add(jMenuSearchTicketReservation);

        jMenuBar.add(jMenuTicketReservation);

        jMenuMovieMarathon.setBackground(new java.awt.Color(153, 153, 255));
        jMenuMovieMarathon.setForeground(new java.awt.Color(0, 0, 102));
        jMenuMovieMarathon.setText("Filmski maraton");

        jMenuNewMovieMarathon.setForeground(new java.awt.Color(0, 0, 102));
        jMenuNewMovieMarathon.setText(" Novi");
        jMenuNewMovieMarathon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewMovieMarathonActionPerformed(evt);
            }
        });
        jMenuMovieMarathon.add(jMenuNewMovieMarathon);

        jMenuSearchMovieMarathon.setForeground(new java.awt.Color(0, 0, 102));
        jMenuSearchMovieMarathon.setText("Pretraži");
        jMenuSearchMovieMarathon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchMovieMarathonActionPerformed(evt);
            }
        });
        jMenuMovieMarathon.add(jMenuSearchMovieMarathon);

        jMenuBar.add(jMenuMovieMarathon);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCurrentUser)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jMenuSearchShowtimeActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        new FShowtimeSearch(this, true, FormMode.FORM_VIEW).setVisible(true);
        // TODO add your handling code here:
    }                                                   

    private void jMenuNewShowtimeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        FShowtime fShowtime = new FShowtime(this, true, FormMode.FORM_ADD, -1);
        fShowtime.setVisible(true);
        setLocationRelativeTo(null);

    }                                                

    private void jMenuNewTicketReservationActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        FReservation fReservation = new FReservation(this, true,FormMode.FORM_ADD,-1);
        fReservation.setVisible(true);
    }                                                         

    private void jMenuNewMovieMarathonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        FMovieMarathon fMovieMarathon = new FMovieMarathon();
        fMovieMarathon.setVisible(true);
    }                                                     

    private void jMenuNewMovieActionPerformed(java.awt.event.ActionEvent evt) {                                              
        FMovie fMovie = new FMovie(this, true,FormMode.FORM_ADD,-1);
        fMovie.setVisible(true);
    }                                             

    private void jMenuSearchMovieMarathonActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        FMovieMarathonSearch fMovieMarathonSearch = new FMovieMarathonSearch(this, true);
        fMovieMarathonSearch.setVisible(true);
    }                                                        

    private void jMenuSearchMovieActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        FMovieSearch fMovieSearch = new FMovieSearch(this, true, FormMode.FORM_VIEW);
        fMovieSearch.setVisible(true);
    }                                                

    private void jMenuSearchTicketReservationActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        FReservationSearch fReservationSearch = new FReservationSearch(null, true);
        fReservationSearch.setVisible(true);
    }                                                            

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLblCurrentUser;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuMovie;
    private javax.swing.JMenu jMenuMovieMarathon;
    private javax.swing.JMenuItem jMenuNewMovie;
    private javax.swing.JMenuItem jMenuNewMovieMarathon;
    private javax.swing.JMenuItem jMenuNewShowtime;
    private javax.swing.JMenuItem jMenuNewTicketReservation;
    private javax.swing.JMenuItem jMenuSearchMovie;
    private javax.swing.JMenuItem jMenuSearchMovieMarathon;
    private javax.swing.JMenuItem jMenuSearchShowtime;
    private javax.swing.JMenuItem jMenuSearchTicketReservation;
    private javax.swing.JMenu jMenuShowtime;
    private javax.swing.JMenu jMenuTicketReservation;
    // End of variables declaration                   

    public void serverClosed() {
        JOptionPane.showMessageDialog(this, "SERVER JE UGASEN.");

    }

  

}
