/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.mavenClient.ui.form;

import rs.ac.bg.fon.ai.nprog.mavenClient.controller.Controller;
import rs.ac.bg.fon.ai.nprog.mavenCommonLib.domain.MovieMarathon;
import rs.ac.bg.fon.ai.nprog.mavenCommonLib.domain.Showtime;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import rs.ac.bg.fon.ai.nprog.mavenClient.ui.component.table.model.MovieMarathonTableModel;

/**
 *
 * @author Ivona
 */
public class FMovieMarathonSearch extends javax.swing.JDialog {

    /**
     * Creates new form FMovieMarathonSearch
     */
    public FMovieMarathonSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareTable();
        try {
            fillForm();
        } catch (Exception ex) {
            Logger.getLogger(FMovieMarathonSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtMarathonName = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jLblRemove = new javax.swing.JLabel();
        jBtnDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMovieMarathons = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtAreaDetails = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLblMarathonName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga filmskih maratona");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga Filmskog Maratona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Ime:");

        jTxtMarathonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtMarathonName.setForeground(new java.awt.Color(0, 0, 102));

        jBtnSearch.setBackground(new java.awt.Color(0, 0, 102));
        jBtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSearch.setText("Pronađi");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jLblRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblRemove.setForeground(new java.awt.Color(153, 0, 0));
        jLblRemove.setText("X Obrisi parametre pretrage");
        jLblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtMarathonName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBtnSearch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLblRemove)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtMarathonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblRemove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnDetails.setBackground(new java.awt.Color(0, 0, 102));
        jBtnDetails.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDetails.setText("Detaljnije");
        jBtnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDetailsActionPerformed(evt);
            }
        });

        jTblMovieMarathons.setBackground(new java.awt.Color(204, 204, 255));
        jTblMovieMarathons.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTblMovieMarathons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblMovieMarathons.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblMovieMarathons);

        jTxtAreaDetails.setEditable(false);
        jTxtAreaDetails.setColumns(20);
        jTxtAreaDetails.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jTxtAreaDetails.setForeground(new java.awt.Color(0, 0, 102));
        jTxtAreaDetails.setRows(5);
        jScrollPane2.setViewportView(jTxtAreaDetails);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Informacije o izabranom maratonu:");

        jLblMarathonName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLblMarathonName.setForeground(new java.awt.Color(0, 0, 102));
        jLblMarathonName.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(jLblMarathonName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jBtnDetails)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLblMarathonName)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>                        

    private void jBtnDetailsActionPerformed(java.awt.event.ActionEvent evt) {                                            
        jLblMarathonName.setText("");
        jTxtAreaDetails.setText("");
        int row = jTblMovieMarathons.getSelectedRow();
        if (row != -1) {
            MovieMarathonTableModel mmtm = (MovieMarathonTableModel) jTblMovieMarathons.getModel();
            MovieMarathon mm = mmtm.getSelectedMarathon(row);
            ArrayList<String> columns = new ArrayList<>();
            ArrayList<String> values = new ArrayList<>();
            columns.add("MovieMarathonId");
            values.add(mm.getMarathonId() + "");
            jLblMarathonName.setText(mm.getName());
            try {
                Controller.getInstance().getShowtimesWithCriteria(columns, values, this);
            } catch (Exception ex) {
                Logger.getLogger(FMovieMarathonSearch.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Izaberite filmski maraton.");
        }

    }                                           

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (jTxtMarathonName.equals("")) {
            return;
        }
        ArrayList<String> columns = new ArrayList<>();
        ArrayList<String> values = new ArrayList<>();
        values.add(jTxtMarathonName.getText());
        columns.add("name");
        List<MovieMarathon> marathons;
        try {
            Controller.getInstance().getMovieMarathonWithCriteria(columns, values, this);

        } catch (Exception ex) {
            Logger.getLogger(FMovieMarathonSearch.class.getName()).log(Level.SEVERE, null, ex);
        }


    }                                          

    private void jLblRemoveMouseClicked(java.awt.event.MouseEvent evt) {                                        
        jTxtMarathonName.setText("");
        jTxtAreaDetails.setText("");
        jLblMarathonName.setText("");
        try {
            fillForm();
        } catch (Exception ex) {
            Logger.getLogger(FMovieMarathonSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton jBtnDetails;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblMarathonName;
    private javax.swing.JLabel jLblRemove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblMovieMarathons;
    private javax.swing.JTextArea jTxtAreaDetails;
    private javax.swing.JTextField jTxtMarathonName;
    // End of variables declaration                   

    private void fillForm() throws Exception {
        Controller.getInstance().getAllMovieMarathons(this);

    }

    public void fillTable(List<MovieMarathon> movieMarathons) {
        if (movieMarathons.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe filmski maraton po zadatoj vrednosti.");
            return;
        }
        JOptionPane.showMessageDialog(this, "Pretraga je završena.");
        MovieMarathonTableModel mmtm = new MovieMarathonTableModel(movieMarathons);
        jTblMovieMarathons.setModel(mmtm);
        jTblMovieMarathons.getColumnModel().getColumn(0).setPreferredWidth(5);

    }

    public void marathonLoadingFailed() {
        JOptionPane.showMessageDialog(this, "Ucitavanje filmskih maratona nije uspelo.");
    }

    public void setShowtimes(List<Showtime> showtimes) {
        try {
            JOptionPane.showMessageDialog(this, "Odabrani maraton je prikazan.");
            for (int i = 0; i < showtimes.size(); i++) {
                if (i == 0) {
                    jLblMarathonName.setText(jLblMarathonName.getText() + "\n Datum: " + showtimes.get(i).getDate() + "\n");
                }

                jTxtAreaDetails.setText(jTxtAreaDetails.getText() + "Vreme: "+showtimes.get(i).getTime() + "\n Film: " + showtimes.get(i).getMovie().getName() + "\n Sala: "+showtimes.get(i).getHall().getName()+"\n\n");
            }
        } catch (Exception ex) {
            Logger.getLogger(FMovieMarathonSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showtimesLoadingFailed() {
        JOptionPane.showMessageDialog(this, "Ucitavanje projekcija nije uspelo.");
    }

    private void prepareTable() {
        JTableHeader header = jTblMovieMarathons.getTableHeader();
        header.setFont(new Font("Tahoma", Font.PLAIN, 16));
        header.setForeground(Color.decode("#12207B"));
        header.setBackground(Color.decode("#C0E2F0"));
    }
}
