/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.mavenClient.ui.form;

import rs.ac.bg.fon.ai.nprog.mavenClient.controller.Controller;
import rs.ac.bg.fon.ai.nprog.mavenCommonLib.domain.MovieMarathon;
import rs.ac.bg.fon.ai.nprog.mavenCommonLib.domain.Showtime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import rs.ac.bg.fon.ai.nprog.mavenClient.ui.component.table.model.ShowtimeTableModel;

/**
 *
 * @author Ivona
 */
public class FMovieMarathon extends javax.swing.JFrame {

    private List<Showtime> addedShowtimes;

    /**
     * Creates new form FFilmskiMaraton
     */
    public FMovieMarathon() {
        initComponents();
        fillTable();
        addedShowtimes = new ArrayList<>();
        setLocationRelativeTo(null);//da
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxtMarathonName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblShowtimesMarathon = new javax.swing.JTable();
        jBtnShowtimeToMarathon = new javax.swing.JButton();
        jBtnSaveMovieMarathon = new javax.swing.JButton();
        jBtnRemoveShowtime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FIlmski maraton");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kreiranje Filmskog Maratona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jTxtMarathonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtMarathonName.setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Naziv maratona:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Projekcije koje se prikazaju na maratonu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        jTblShowtimesMarathon.setBackground(new java.awt.Color(204, 204, 255));
        jTblShowtimesMarathon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTblShowtimesMarathon.setForeground(new java.awt.Color(0, 0, 102));
        jTblShowtimesMarathon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblShowtimesMarathon);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );

        jBtnShowtimeToMarathon.setBackground(new java.awt.Color(0, 0, 102));
        jBtnShowtimeToMarathon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnShowtimeToMarathon.setForeground(new java.awt.Color(255, 255, 255));
        jBtnShowtimeToMarathon.setText("Dodaj projekciju");
        jBtnShowtimeToMarathon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowtimeToMarathonActionPerformed(evt);
            }
        });

        jBtnSaveMovieMarathon.setBackground(new java.awt.Color(0, 0, 102));
        jBtnSaveMovieMarathon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnSaveMovieMarathon.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveMovieMarathon.setText("Sacuvaj filmski maraton");
        jBtnSaveMovieMarathon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveMovieMarathonActionPerformed(evt);
            }
        });

        jBtnRemoveShowtime.setBackground(new java.awt.Color(0, 0, 102));
        jBtnRemoveShowtime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnRemoveShowtime.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRemoveShowtime.setText("Ukloni projekciju");
        jBtnRemoveShowtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoveShowtimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtMarathonName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jBtnShowtimeToMarathon)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnRemoveShowtime)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnSaveMovieMarathon)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMarathonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnShowtimeToMarathon)
                    .addComponent(jBtnRemoveShowtime))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSaveMovieMarathon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jBtnShowtimeToMarathonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        FShowtimeSearch fShowtimeSearch = new FShowtimeSearch(this, true, FormMode.FORM_SELECT_MULTIPLE);
        fShowtimeSearch.setVisible(true);
    }                                                      

    private void jBtnSaveMovieMarathonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        ShowtimeTableModel showtimeTableModel = (ShowtimeTableModel) jTblShowtimesMarathon.getModel();
        List<Showtime> showtimes = showtimeTableModel.getAllShowtimes();
        if (jTxtMarathonName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Unesite naziv filmskog maratona.");
            return;
        }
        if (showtimes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate dodati projekcije za filmski maraton.");
            return;
        }
        String name = jTxtMarathonName.getText();
        MovieMarathon movieMarathon = new MovieMarathon(name, controller.Controller.getInstance().getCurrentUser());
        try {
            Controller.getInstance().saveMovieMarathon(movieMarathon, showtimes,this);

        } catch (Exception ex) {
            Logger.getLogger(FMovieMarathon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void jBtnRemoveShowtimeActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        int row = jTblShowtimesMarathon.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Morate odabrati projekciju.");
            return;
        } else {
            ShowtimeTableModel showtimeTableModel = (ShowtimeTableModel) jTblShowtimesMarathon.getModel();
            showtimeTableModel.removeShowtime(row);
        }
    }                                                  

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBtnRemoveShowtime;
    private javax.swing.JButton jBtnSaveMovieMarathon;
    private javax.swing.JButton jBtnShowtimeToMarathon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblShowtimesMarathon;
    private javax.swing.JTextField jTxtMarathonName;
    // End of variables declaration                   

    private void fillTable() {
        ShowtimeTableModel showtimeTableModel = new ShowtimeTableModel();
        jTblShowtimesMarathon.setModel(showtimeTableModel);
    }

    private boolean checkMovies(List<Showtime> showtimes, Showtime sh) {
        for (Showtime s : showtimes) {
            if (s == sh) {
                return false;
            }
            if (s.getMovie().equals(sh.getMovie())) {
                return false;
            }
        }
        return true;
    }

    public List<Showtime> getAddedShowtimes() {
        return addedShowtimes;
    }

    public void addShowtimeToMarathon(Showtime s) {
        addedShowtimes.add(s);
        ShowtimeTableModel stm = (ShowtimeTableModel) jTblShowtimesMarathon.getModel();
        stm.addShowtime(s);
    }

    public void mmCreated() {
        JOptionPane.showMessageDialog(this, "Sistem je zapamtio maraton");
        dispose();
    }

    public void mmNotCreated() {
        JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti maraton.");
    }
}
