
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.mavenClient.ui.form;

import rs.ac.bg.fon.ai.nprog.mavenClient.controller.Controller;
import rs.ac.bg.fon.ai.nprog.mavenCommonLib.domain.Reservation;
import rs.ac.bg.fon.ai.nprog.mavenCommonLib.domain.Showtime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivona
 */
public class FReservation extends javax.swing.JDialog {

    Showtime showtime;

    /**
     * Creates new form FRezervacija
     */
    public FReservation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtNameLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jBtnSaveReservation = new javax.swing.JButton();
        jTxtShowtime = new javax.swing.JTextField();
        jtxtDate = new javax.swing.JTextField();
        jTxtMovie = new javax.swing.JTextField();
        jBttnSelectShowtime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservation");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rezervacija", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Film:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Projekcija:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Datum:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Ime i prezime:");

        jTxtNameLastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtNameLastname.setForeground(new java.awt.Color(0, 0, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Email:");

        jTxtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtEmail.setForeground(new java.awt.Color(0, 0, 102));

        jBtnSaveReservation.setBackground(new java.awt.Color(0, 0, 102));
        jBtnSaveReservation.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveReservation.setText("Sačuvaj");
        jBtnSaveReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveReservationActionPerformed(evt);
            }
        });

        jTxtShowtime.setEditable(false);
        jTxtShowtime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtShowtime.setForeground(new java.awt.Color(0, 0, 102));

        jtxtDate.setEditable(false);
        jtxtDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtDate.setForeground(new java.awt.Color(0, 0, 102));

        jTxtMovie.setEditable(false);
        jTxtMovie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtMovie.setForeground(new java.awt.Color(0, 0, 102));
        jTxtMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMovieActionPerformed(evt);
            }
        });

        jBttnSelectShowtime.setBackground(new java.awt.Color(0, 0, 102));
        jBttnSelectShowtime.setForeground(new java.awt.Color(255, 255, 255));
        jBttnSelectShowtime.setText("...");
        jBttnSelectShowtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSelectShowtimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtNameLastname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtShowtime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnSaveReservation, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBttnSelectShowtime)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtShowtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBttnSelectShowtime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTxtNameLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jBtnSaveReservation)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveReservationActionPerformed
        if(showtime==null){
            JOptionPane.showMessageDialog(this, "Morate odabrati projekciju!");
            return;
        }
        Reservation reservation = new Reservation(jTxtNameLastname.getText(), jTxtEmail.getText(), Controller.getInstance().getCurrentUser(), showtime);
        try {
            Controller.getInstance().saveReservation(reservation, this);
        } catch (Exception ex) {
            Logger.getLogger(FReservation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBtnSaveReservationActionPerformed

    private void jBttnSelectShowtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSelectShowtimeActionPerformed
        FShowtimeSearch fShowtimeSearch = new FShowtimeSearch(null, true, FormMode.FORM_SELECT);
        fShowtimeSearch.setVisible(true);
//        if(fShowtimeSearch.getShowtime().equals(null))return;
        try {
            showtime = fShowtimeSearch.getShowtime();
        } catch (Exception ex) {
        }

        prepareShowtime();
    }//GEN-LAST:event_jBttnSelectShowtimeActionPerformed

    private void jTxtMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMovieActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSaveReservation;
    private javax.swing.JButton jBttnSelectShowtime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtMovie;
    private javax.swing.JTextField jTxtNameLastname;
    private javax.swing.JTextField jTxtShowtime;
    private javax.swing.JTextField jtxtDate;
    // End of variables declaration//GEN-END:variables

    private void prepareShowtime() {
        if (showtime != null) {
            jTxtMovie.setText(showtime.getMovie().toString());
            jTxtShowtime.setText(showtime.toString());
            jtxtDate.setText(showtime.getDate() + "");

        }
    }

    public void reservationIsNotSaved() {
        JOptionPane.showMessageDialog(this, "Sistem nije zapamtio rezervaciju.");
    }

    public void reservationIsSaved() {
        JOptionPane.showMessageDialog(this, "Sistem je zapamtio rezervaciju.");

        dispose();
    }

    public void invalidEmail() {
        JOptionPane.showMessageDialog(this, "Unesite ispravan email.");
    }

}
