package rs.ac.bg.fon.ai.nprog.mavenServer.form;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.JTableHeader;

import com.google.gson.JsonArray;

import rs.ac.bg.fon.ai.nprog.mavenServer.controller.Controller;
import rs.ac.bg.fon.ai.nprog.mavenServer.form.model.HistoryTableModel;
import rs.ac.bg.fon.ai.nprog.mavenServer.form.model.UserTableModel;
import rs.ac.bg.fon.ai.nprog.mavenServer.history.History;
import rs.ac.bg.fon.ai.nprog.mavenServer.history.HistoryObject;

public class FHistory extends javax.swing.JFrame {

	/**
	 * Creates new form FHistory
	 */
	public FHistory(List<HistoryObject> history) {
		setLocationRelativeTo(null);
		setResizable(false);
		initComponents();
		fillForm(history);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
//		jtxtHistory = new javax.swing.JTextArea();
		jTblHistory = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search History",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 0, 102))); // NOI18N

//		jtxtHistory.setColumns(20);
//		jtxtHistory.setRows(5);
//		jScrollPane1.setViewportView(jtxtHistory);

		jTblHistory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jTblHistory.setForeground(new java.awt.Color(0, 0, 102));
		jTblHistory.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Username", "Firstname", "Lastname" }));
		jTblHistory.setGridColor(new java.awt.Color(204, 204, 255));
		jScrollPane1.setViewportView(jTblHistory);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(24, Short.MAX_VALUE).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
//	private javax.swing.JTextArea jtxtHistory;
	private javax.swing.JTable jTblHistory;

	// End of variables declaration


	public void fillForm(List<HistoryObject> history) {
		HistoryTableModel userTableModel = new HistoryTableModel(history);
		jTblHistory.setModel(userTableModel);
		JTableHeader header = jTblHistory.getTableHeader();
		header.setFont(new Font("Tahoma", Font.PLAIN, 19));
		header.setForeground(Color.decode("#12207B"));
		header.setBackground(Color.decode("#C0E2F0"));
		jTblHistory.getColumnModel().getColumn(0).setPreferredWidth(70);
		jTblHistory.getColumnModel().getColumn(1).setPreferredWidth(110);
		jTblHistory.getColumnModel().getColumn(2).setPreferredWidth(70);
	}
}
