package rs.ac.bg.fon.ai.nprog.mavenServer.form;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.JTableHeader;

import com.google.gson.JsonArray;
import com.mysql.cj.protocol.FullReadInputStream;

import rs.ac.bg.fon.ai.nprog.mavenServer.controller.Controller;
import rs.ac.bg.fon.ai.nprog.mavenServer.form.model.HistoryTableModel;
import rs.ac.bg.fon.ai.nprog.mavenServer.form.model.UserTableModel;
import rs.ac.bg.fon.ai.nprog.mavenServer.history.History;
import rs.ac.bg.fon.ai.nprog.mavenServer.history.HistoryObject;

public class FHistory extends javax.swing.JFrame {

	/**
	 * Creates new form FHistory
	 */
	public FHistory(List<HistoryObject> history) {
		setLocationRelativeTo(null);
//		setResizable(false);
		initComponents();
	
		fillForm(history);
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Istorija");

        jTableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableHistory);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ISTORIJA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHistory;
    // End of variables declaration     


	public void fillForm(List<HistoryObject> history) {
		HistoryTableModel userTableModel = new HistoryTableModel(history);
		jTableHistory.setModel(userTableModel);
		JTableHeader header = jTableHistory.getTableHeader();
		header.setFont(new Font("Tahoma", Font.PLAIN, 19));
		header.setForeground(Color.decode("#12207B"));
		header.setBackground(Color.decode("#C0E2F0"));
		jTableHistory.getColumnModel().getColumn(0).setPreferredWidth(70);
		jTableHistory.getColumnModel().getColumn(1).setPreferredWidth(150);
		jTableHistory.getColumnModel().getColumn(2).setPreferredWidth(70);
		jTableHistory.getColumnModel().getColumn(4).setPreferredWidth(250);

	}
}
