/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.mavenServer.form;

import rs.ac.bg.fon.ai.nprog.mavenCommonLib.domain.User;
import rs.ac.bg.fon.ai.nprog.mavenServer.thread.RefreshUsersThread;
import rs.ac.bg.fon.ai.nprog.mavenServer.controller.Controller;
import rs.ac.bg.fon.ai.nprog.mavenServer.form.model.UserTableModel;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Ivona
 */
public class FOnlineUsers extends javax.swing.JDialog {

    /**
     * Creates new form FOnlineUsers
     */
    public FOnlineUsers(java.awt.Frame parent, boolean modal, List<User> users) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareTable();
        startRefreshUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblOnlineUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Online users");

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 102));

        jTblOnlineUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTblOnlineUsers.setForeground(new java.awt.Color(0, 0, 102));
        jTblOnlineUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Firstname", "Lastname"
            }
        ));
        jTblOnlineUsers.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTblOnlineUsers);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblOnlineUsers;
    // End of variables declaration//GEN-END:variables

    private void prepareTable() {
        UserTableModel userTableModel = new UserTableModel(Controller.getInstance().getOnlineUsers());
        jTblOnlineUsers.setModel(userTableModel);
        JTableHeader header = jTblOnlineUsers.getTableHeader();
        header.setFont(new Font("Tahoma", Font.PLAIN, 19));
        header.setForeground(Color.decode("#12207B"));
        header.setBackground(Color.decode("#C0E2F0"));
        jTblOnlineUsers.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTblOnlineUsers.getColumnModel().getColumn(1).setPreferredWidth(110);
        jTblOnlineUsers.getColumnModel().getColumn(2).setPreferredWidth(110);
    }

    private void startRefreshUsers() {
        System.out.println("POZIVAM REFRESH");
        RefreshUsersThread refreshUsersThread = new RefreshUsersThread(jTblOnlineUsers);
        refreshUsersThread.start();
    }
}
