/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.mavenServer.form.config.server;

import javax.swing.JOptionPane;
import rs.ac.bg.fon.ai.nprog.mavenServer.configuration.*;
import rs.ac.bg.fon.ai.nprog.mavenServer.controller.Controller;
/**
 *
 * @author Ivona
 */
public class FServerConfig extends javax.swing.JFrame {

    /**
     * Creates new form FServerConfig
     */
    public FServerConfig() {
        initComponents();
        setLocationRelativeTo(null);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtPortNumber = new javax.swing.JTextField();
        jBttnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server Configuration");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Broj porta:");

        jTxtPortNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtPortNumber.setForeground(new java.awt.Color(0, 0, 102));

        jBttnEdit.setBackground(new java.awt.Color(204, 204, 255));
        jBttnEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBttnEdit.setForeground(new java.awt.Color(0, 0, 102));
        jBttnEdit.setText("Izmeni");
        jBttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBttnEdit))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jBttnEdit)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnEditActionPerformed
        if (jTxtPortNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite broj porta");
            return;
        }
        try {
            int port = Integer.parseInt(jTxtPortNumber.getText());

            if (port < 0 || port > 65535) {
                JOptionPane.showMessageDialog(this, "Port mora biti broj u rasponu od 0 do 65535");
            }
            int answer = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da promenite broj porta?");
            if (answer == 0) {
                Controller.getInstance().changePortNumber(port,this);
                dispose();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Broj porta mora biti broj u rasponu od 0 do 65535");
        }
    }//GEN-LAST:event_jBttnEditActionPerformed

    private void prepareForm() {
        jTxtPortNumber.setText(Configuration.getInstance().getPort() + "");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtPortNumber;
    // End of variables declaration//GEN-END:variables

    public void notChanged() {
            JOptionPane.showMessageDialog(this, "Broj porta nije promenjen!");
    }
}
